"""Add priority column to leads table

Revision ID: c85529f44a74
Revises: add_status_change_ts
Create Date: 2026-06-12 14:08:30.135228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85529f44a74'
down_revision: Union[str, Sequence[str], None] = 'add_status_change_ts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first to handle existing rows
    op.add_column('leads', sa.Column('priority', sa.String(length=50), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE leads SET priority = 'Media' WHERE priority IS NULL")
    # Make the column non-nullable
    op.alter_column('leads', 'priority', nullable=False)
    op.create_index('idx_leads_priority', 'leads', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_leads_priority', table_name='leads')
    op.drop_column('leads', 'priority')
    # ### end Alembic commands ###
